name: paul_prod

services:

  db:
    container_name: paul_db
    extends:
      file: docker-compose.base.yml
      service: db_base_psql

  app:
    container_name: paul_app
    extends:
      file: docker-compose.base.yml
      service: app_base
    volumes:
      - ./backend/media:/var/www/paul/backend/media
    environment:
      ENVIRONMENT: "production"
      DATABASE_HOST: "paul_db"
    depends_on:
      - db

volumes:
  paul_psql:
