services:

  db_base_psql:
    image: postgres:17.5
    env_file:
      - .env
    volumes:
      - paul_psql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT:-5432}:5432"

  app_base:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_ENGINE: "postgresql"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      PYTHONUNBUFFERED: "1"

  app_dev_base:
    extends:
      service: app_base
    build:
      dockerfile: ./docker/dockerfiles/Dockerfile.dev
    volumes:
      - ./backend:/var/www/paul/backend
      - ./frontend/src:/var/www/paul/frontend/src
    ports:
      - "${WEBAPP_PORT:-8080}:8000"
      - "${STATIC_PORT:-3000}:3000"
