"""
Django settings for Paul.

Initially generated by 'django-admin startproject' using Django 5.2.
Broken down into multiple files for better organization and readability.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from .authentication import *
from .base import *
from .cache import *
from .databases import *
from .django_q import *
from .email import *
from .environment import *
from .frontend import *
from .installed_apps import *
from .l10n import *
from .logging import *
from .ngohub_connection import *
from .query_params import *
from .recaptcha import *
from .social_auth import *
from .storages import *
from .templates import *
