from .environment import env

# reCAPTCHA

RECAPTCHA_PUBLIC_KEY = env("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = env("RECAPTCHA_PRIVATE_KEY")
RECAPTCHA_REQUIRED_SCORE = env("RECAPTCHA_REQUIRED_SCORE")

RECAPTCHA_ENABLED = True if RECAPTCHA_PUBLIC_KEY else False
