# Generated by Django 5.2.3 on 2025-07-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["pk"], "verbose_name": "Utilizator", "verbose_name_plural": "Users"},
        ),
    ]
