# Generated by Django 5.2.4 on 2025-07-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin'), ('super admin', 'Super Admin'), ('support admin', 'Support Admin')], default='user', max_length=50, verbose_name='role'),
        ),
    ]
