# Generated by Django 5.2.4 on 2025-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_main_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ngohub_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='The ID of the user in NGO Hub, if applicable.', null=True, unique=True, verbose_name='NGO Hub ID'),
        ),
    ]
