# Generated by Django 5.2.4 on 2025-08-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_ngohub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='We do not use this field', max_length=150, null=True, verbose_name='nume utilizator'),
        ),
    ]
