# Generated by Django 5.2.5 on 2025-08-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["pk"],
                "permissions": [("change_role", "Can change a user's role")],
                "verbose_name": "Utilizator",
                "verbose_name_plural": "Users",
            },
        ),
    ]
