name: Backend Check

on:
  push:
    branches:
      - '*'
      - 'main'
#    paths:
#      - 'backend/**.py'
#      - 'backend/uv.lock'
#      - 'backend/pyproject.toml'
#      - 'Dockerfile*'
#      - 'docker-compose*.yml'
#      - '.github/workflows/backend_check.yml'
  pull_request:
    branches:
      - 'main'
#    paths:
#      - 'backend/**.py'
#      - 'backend/uv.lock'
#      - 'backend/pyproject.toml'
#      - 'Dockerfile*'
#      - 'docker-compose*.yml'
#      - '.github/workflows/backend_check.yml'

jobs:

  formatting_with_black:
    name: Run Black formatting check
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "./backend/pyproject.toml"

    - name: Install Black with uv
      working-directory: ./backend
      run: |
        uv sync --only-group black

    - name: Check formatting with Black
      working-directory: ./backend
      run: |
        uv run black --check .


  linting_with_ruff:
    name: Run Ruff linting check
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "./backend/pyproject.toml"

    - name: Install Black & Ruff with uv
      working-directory: ./backend
      run: |
        uv sync --only-group ruff

    - name: Lint files using Ruff
      working-directory: ./backend
      run: |
        uv run ruff check .


  checking_migrations:
    name: Check for migrations
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "./backend/pyproject.toml"

    - name: Install dependencies
      working-directory: ./backend
      run: |
        uv sync

    - name: Check for migrations
      working-directory: ./backend
      run: |
        set -a
        uv run ./manage.py makemigrations --check --dry-run
        set +a


  tests:
    name: Run backend tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:17.5
        env:
          POSTGRES_DB: paul
          POSTGRES_USER: user
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "./backend/pyproject.toml"

    - name: Install dependencies
      run: |
        set -a
        source .env.example
        set +a
        cd ./backend
        uv sync
        sudo apt-get install gettext
        uv run ./manage.py compilemessages

    - name: Run tests
      env:
        DATABASE_NAME: paul
        DATABASE_USER: user
        DATABASE_PASSWORD: secret
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: 5432
      working-directory: ./backend
      run: |
        uv run ./manage.py wait_for_db
        uv run ./manage.py test


  codeql_analysis:
    name: Analyze code using CodeQL
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
